version: "3"
services:
  db:
    image: mysql:5.7.19
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:5.5.2
  app:
    build: .
    volumes:
      - .:/app
      - gems_cache:/gems
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
      - elasticsearch
      - rabbitmq
volumes:
  db-data:
  gems_cache:
